#! /usr/bin/octave -q

list = {"adenine_thymine_stack","adenine_thymine_wcc1","ar_ar","ar_kr","c10h8_c10h8_pc",...
        "c10h8_c10h8_p","c10h8_c10h8_tc","c10h8_c10h8_t","c2h2_c2h2","c2h4_c2h2","c2h4_c2h4",...
        "c2h4_hf","c6h6_c6h6_pd","c6h6_c6h6_stack","c6h6_c6h6_t","c6h6_ch4","c6h6_h2o","c6h6_hcn"...
        "c6h6_ne","c6h6_nh3","cf4_cf4","ch3cl_hcl","ch3cn_ch3cn","ch3f_ch3f","ch3sh_hcl","ch4_c2h4",...
        "ch4_ch4","ch4_hf","ch4_ne","ch4_nh3","co2_co2","fcl_he","formamide_formamide","h2co2_h2co2",...
        "h2co_h2co","h2o_h2o","h2s_h2s","h2s_hcl","hcl_hcl","hcn_ch3sh","hcn_hf","he_ar",...
        "he_fcl","he_he","he_kr","he_n2_l","he_n2_t","he_ne","hf_hf","indole_c6h6_stack","indole_c6h6_t",...
        "kr_kr","ne_ar","ne_kr","ne_ne","nh3_h2o","nh3_nh3","ocs_ocs","phenol_phenol","pyrazine_pyrazine",...
        "pyridoxine_aminopyridine","sih4_ch4","sih4_hf","uracil_uracil_hb","uracil_uracil_stack"};

for i = 1:length(list)
  mol = mol_readxyz(sprintf("%s.xyz",list{i}));
  rep = mol_ball(mol);
  rep = mol_stick(mol,rep);
  rep = rep_setdefaultscene_tessel(rep,:,"direct-noshadow");
  name = sprintf("%2.2d_%s",i,list{i});
  rep_write_pov(rep,sprintf("%s.pov",name));
  run_povray(name);
endfor
